      # ---------------------------------------------------------------
      # AI SECURE REMEDIATION ASSESSMENT (NVIDIA)
      # ---------------------------------------------------------------
      - name: 🤖 Agent 3 - AI Secure Remediation Assessment
        if: always()
        env:
          NVDAI_API_KEY: ${{ secrets.NVIDIA_API_KEY }}
          NVDAI_MODEL: meta/llama-3.1-70b-instruct
        run: |
          set -euo pipefail

          mkdir -p reports

          if [ ! -f reports/SECURE_REMEDIATION_REPORT.md ]; then
            echo "::warning::SECURE_REMEDIATION_REPORT.md not found."

            cat > reports/AI_SECURE_REMEDIATION_SUMMARY.md <<EOF
          # AI Secure Remediation Assessment

          ## Executive Summary

          Secure remediation report was not found.

          ## Deployment Recommendation

          MANUAL REVIEW REQUIRED
          EOF

            exit 0
          fi

          REPORT_CONTENT=$(head -c 20000 reports/SECURE_REMEDIATION_REPORT.md)

          cat > payload.json <<EOF
          {
            "model":"${NVDAI_MODEL}",
            "max_tokens":2500,
            "messages":[
              {
                "role":"system",
                "content":"You are an Enterprise DevSecOps AI Security Validation Agent.

Your responsibility is to analyze the secure remediation report generated by the Sonar-Trivy Auto Remediation Agent.

Use ONLY the information contained in the report.

Never invent findings.

Return ONLY Markdown in the required assessment format."
              },
              {
                "role":"user",
                "content":$(jq -Rs . <<< "$REPORT_CONTENT")
              }
            ]
          }
          EOF

          RESPONSE=$(curl -s https://integrate.api.nvidia.com/v1/chat/completions \
            -H "Authorization: Bearer $NVDAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d @payload.json)

          echo "$RESPONSE" | jq -r '.choices[0].message.content // ""' \
            > reports/AI_SECURE_REMEDIATION_SUMMARY.md

          rm -f payload.json

          echo "=============================="
          cat reports/AI_SECURE_REMEDIATION_SUMMARY.md
          echo "=============================="
