package com.owasp.lab.controller;

import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.io.*;
import java.util.Base64;
import java.util.regex.Pattern;

/**
 * Insecure deserialisation demo.
 *
 * VULNERABILITY (OWASP A08:2021 - Software and Data Integrity Failures):
 *
 * This endpoint accepts a base64-encoded serialized Java object in the
 * request body and deserialises it using {@link ObjectInputStream} without
 * any filtering.  Java native deserialisation can lead to Remote Code
 * Execution via gadget chains (commons-collections, spring-core, etc.).
 *
 * Try with a malicious payload generated by ysoserial:
 *   java -jar ysoserial.jar CommonsCollections6 "calc.exe" | base64
 *
 * DO NOT expose this on any network.
 */
@RestController
@RequestMapping("/api/deserialize")
public class InsecureDeserializationController {

    // Whitelist of fully-qualified class names that may be deserialised.
    // Anything outside this list is rejected before readObject() is called,
    // which neutralises gadget-chain RCE (CWE-502, OWASP A08:2021).
    private static final Pattern ALLOWED_CLASSES = Pattern.compile(
            "^("
                    + "java\\.lang\\.(String|Long|Integer|Boolean|Double|Float|Byte|Short|Character|Number|Object)"
                    + "|java\\.util\\.(HashMap|LinkedHashMap|ArrayList|LinkedList|HashSet|TreeSet|Date|UUID)"
                    + "|com\\.owasp\\.lab\\.model\\.[A-Za-z0-9_]+"
                    + ")$"
    );

    @PostMapping(consumes = MediaType.TEXT_PLAIN_VALUE)
    public ResponseEntity<?> deserialize(@RequestBody String body) throws Exception {
        byte[] bytes = Base64.getDecoder().decode(body);
        // FIX (CWE-502, OWASP A08:2021): install an ObjectInputFilter that
        // resolves each class about to be deserialised and only allows the
        // whitelisted packages above. The JVM consults the filter before
        // allocating any class, so gadget chains from spring-core /
        // commons-collections / etc. are blocked at the source.
        try (ObjectInputStream ois = new ObjectInputStream(new ByteArrayInputStream(bytes))) {
            ois.setObjectInputFilter(info -> {
                Class<?> resolved = info.serialClass();
                if (resolved == null) {
                    return ObjectInputFilter.Status.UNDECIDED;
                }
                String name = resolved.getName();
                if (ALLOWED_CLASSES.matcher(name).matches()) {
                    return ObjectInputFilter.Status.ALLOWED;
                }
                return ObjectInputFilter.Status.REJECTED;
            });
            Object o = ois.readObject();
            return ResponseEntity.ok("Deserialized: " + o.getClass().getName());
        }
    }
}
